#!/bin/bash
# Build ReadItSoon Companion macOS menu bar app.
#
# Usage:
#   BASE_URL=https://readitsoon.com \
#   USER_EMAIL=you@kindle.com \
#   AUTH_TOKEN=your64hextoken \
#   ./build.sh
#
# Produces: ReadItSoonCompanion.app

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

# --- Validate credentials ---
if [ -z "$BASE_URL" ] || [ -z "$USER_EMAIL" ] || [ -z "$AUTH_TOKEN" ]; then
    echo "Error: set BASE_URL, USER_EMAIL, and AUTH_TOKEN environment variables."
    echo "Example:"
    echo "  BASE_URL=https://readitsoon.com USER_EMAIL=you@kindle.com AUTH_TOKEN=abc123 ./build.sh"
    exit 1
fi

# --- Inject credentials ---
cat > Sources/ReadItSoonCompanion/Credentials.swift << EOF
// Auto-generated by build.sh — do not edit manually.
enum Credentials {
    static let baseURL    = "$BASE_URL"
    static let userEmail  = "$USER_EMAIL"
    static let authToken  = "$AUTH_TOKEN"
}
EOF

echo "→ Building..."
swift build -c release 2>&1

BINARY=".build/release/ReadItSoonCompanion"
APP="ReadItSoonCompanion.app"

# --- Bundle ---
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS"
mkdir -p "$APP/Contents/Resources"

cp "$BINARY" "$APP/Contents/MacOS/ReadItSoonCompanion"
cp "assets/AppIcon.icns" "$APP/Contents/Resources/AppIcon.icns"

cat > "$APP/Contents/Info.plist" << 'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key>
    <string>ReadItSoonCompanion</string>
    <key>CFBundleName</key>
    <string>ReadItSoon Companion</string>
    <key>CFBundleIdentifier</key>
    <string>com.readitsoon.companion</string>
    <key>CFBundleVersion</key>
    <string>1.0.0</string>
    <key>CFBundleIconFile</key>
    <string>AppIcon</string>
    <key>LSMinimumSystemVersion</key>
    <string>12.0</string>
    <key>LSUIElement</key>
    <true/>
</dict>
</plist>
PLIST

echo ""
echo "✓ Built: $APP"
echo ""
echo "Run:   open $APP"
echo "Or:    cp -r $APP /Applications/"
