// Auto-generated by build.sh — do not edit manually.
enum Credentials {
    static let baseURL    = "https://readitsoon.chiq.me"
    static let userEmail  = "guillermo.siliceo@kindle.com"
    static let authToken  = "56411c906131ab10419d8216968afc369b09ecd28717edbe2e8cca55b8f3c653"
}
